SELECT 
    CASE QUARTER(DIFFERENTIATION_DATE)
        WHEN 1 THEN '1Q'
        WHEN 2 THEN '2Q'
        WHEN 3 THEN '3Q'
        WHEN 4 THEN '4Q'
    END AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM 
    ECOLI_DATA
GROUP BY 
    CASE QUARTER(DIFFERENTIATION_DATE)
        WHEN 1 THEN '1Q'
        WHEN 2 THEN '2Q'
        WHEN 3 THEN '3Q'
        WHEN 4 THEN '4Q'
    END
ORDER BY 
    QUARTER;
