SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
    -- 각 연도 별로 분할하여 연도 별 최대 값을 구한 다음 각 행의 대장균 크기 빼기
    ID
FROM
    ECOLI_DATA
ORDER BY
    YEAR,
    YEAR_DEV;
